### ISSUE TITLE
Missing function

### ISSUE THREAD

**Issue by thegamerx1** [helsmy/vscode-autohotkey#6]
the function `OnClipboardChange` is missing
https://www.autohotkey.com/docs/commands/OnClipboardChange.htm#function

**Comment by helsmy** [comment]
The hint information of built-in functions is achieved by convert function information of scite4ahk. Since scite4ahk is not updated for a loooong time, the information are outdate with a lot of missing functions. Because add them by hand is such a boring work, I only add some of them often used by me. 
As What's New-4 in readme, I need some help to finish it. If you are willing to help, please just post it here and follow the example below:

```json
[
    {
        "name": "Function name",
        "params": [
            {
                "name": "Parameter name",
                "isOptional": "true of false",
                "defaultVal": "defaulValue(Optional) the defaul value of an optional parameter"
            }
            , "..."
        ] 
    }, "..."
]
```

**Comment by thegamerx1** [comment]
```json
[
    {
        "name": "OnClipboardChange",
        "params": [
            {
                "name": "Func",
                "isOptional": false
			},
			{
				"name": "AddRemove",
				"isOptional": true,
				"defaultVal": 1
			}
        ]
	},
	{
		"name": "Ord",
		"params": [
			{
				"name": "String",
				"isOptional": false
			}
		]
	}
]
```
