### ISSUE TITLE
Autocomplete hint

### ISSUE THREAD

**Issue by Oliver-Patterson** [helsmy/vscode-autohotkey#8]
I would like to be able to see where the (include) function comes from, is it possible to add to hint?

(Sorry for my English)

**Comment by helsmy** [comment]
This is very easy to finish. It will be added on the next version.:relaxed:

**Comment by Oliver-Patterson** [comment]
Can you add this information not immediately after the function, but through a line?

> funcName(....)
> 
> Include from ....

**Comment by Oliver-Patterson** [comment]
![image](https://user-images.githubusercontent.com/78804737/113498230-ccee0400-9513-11eb-8c06-25df27f485f8.png)
It also does not write the file where the function was taken from. Perhaps it is better to put it in the settings.

Sorry for the English, I'm using a translator. <3

**Comment by Oliver-Patterson** [comment]
And why is the value not written in ""? It is not empty.

**Comment by helsmy** [comment]
1. for the first, I add a newline between them. But, vscode dosen't display it. I don't konw why. May be caused by the display type.
2. I thought it needn't to hint twice on signture help and singture is already very looooooong now.
3. I am not quite clear about what the code for. Since ahk silent fail and return `""` at most time, it is better to debuging and finding out more on what happends on runing. In case, I recommend zero-plusplus's debug extension. And you'd better to ask ahk related question on the offical forum or offical discord channel.

**Comment by Oliver-Patterson** [comment]
3. I mean that... Autocomplete hint does not show the optional value for the encoding argument (CP1251), instead it shows "".
(Perhaps I didn't understand you correctly, because it is difficult to understand the translation into my language, or not put it this way / translated it. Sorry.)

**Comment by helsmy** [comment]
Sorroy, I got misunderstanded by tanslator. I will to try fix it. But, I am working on other parts of this extension now. It may be take a few time to be fixed.

**Comment by Oliver-Patterson** [comment]
This issue has been resolved.
